-- Seed data for Meiringen & Haslital

insert into public.organizations (name, slug, description, category, website_url, email, phone, address, latitude, longitude, languages, image_url) values
('Kulturverein Meiringen', 'kulturverein-meiringen', 'Kulturelle Veranstaltungen und Projekte in Meiringen.', 'culture', 'https://example.com/kulturverein', 'info@kulturverein-meiringen.ch', '+41 33 000 10 01', 'Bahnhofstrasse 1, 3860 Meiringen', 46.7275, 8.1875, array['de','gsw'], null),
('Sportclub Haslital', 'sportclub-haslital', 'Sportangebote für alle Altersgruppen im Haslital.', 'sport', 'https://example.com/sportclub', 'kontakt@sportclub-haslital.ch', '+41 33 000 10 02', 'Hauptstrasse 12, 3860 Meiringen', 46.7280, 8.1880, array['de','en'], null),
('Integrationszentrum Oberhasli', 'integrationszentrum-oberhasli', 'Sprachkurse und Integrationsangebote für Neuankömmlinge.', 'integration', 'https://example.com/integration', 'info@integration-oberhasli.ch', '+41 33 000 10 03', 'Kirchgasse 5, 3860 Meiringen', 46.7268, 8.1862, array['de','en','fr','pt'], null),
('Musikgesellschaft Meiringen', 'musikgesellschaft-meiringen', 'Traditionelle und moderne Musikveranstaltungen.', 'music', null, 'musik@meiringen.ch', '+41 33 000 10 04', 'Dorfplatz 3, 3860 Meiringen', 46.7272, 8.1870, array['de','gsw'], null),
('Naturfreunde Haslital', 'naturfreunde-haslital', 'Wanderungen und Naturerlebnisse in der Region.', 'nature', 'https://example.com/naturfreunde', 'natur@haslital.ch', null, 'Talstrasse 20, 3860 Meiringen', 46.7290, 8.1900, array['de','en','fr','it'], null),
('Seniorenverein Meiringen', 'seniorenverein-meiringen', 'Soziale Treffen und Aktivitäten für Senioren.', 'social', null, 'senioren@meiringen.ch', '+41 33 000 10 05', 'Schulhausweg 2, 3860 Meiringen', 46.7265, 8.1855, array['de','gsw','rm'], null),
('Volksschule Meiringen', 'volksschule-meiringen', 'Bildungsangebote und Gemeindeveranstaltungen.', 'education', 'https://example.com/schule', 'schule@meiringen.ch', '+41 33 000 10 06', 'Schulhausstrasse 8, 3860 Meiringen', 46.7285, 8.1890, array['de'], null),
('Brass Band Haslital', 'brass-band-haslital', 'Konzerte und Auftritte der regionalen Brass Band.', 'music', null, 'band@haslital.ch', null, 'Meiringen', 46.7275, 8.1875, array['de','en'], null),
('Gemeinde Meiringen', 'gemeinde-meiringen', 'Offizielle Gemeindeveranstaltungen und Märkte.', 'festival', 'https://www.meiringen.ch', 'info@meiringen.ch', '+41 33 972 11 11', 'Rathaus, 3860 Meiringen', 46.7270, 8.1868, array['de','gsw','en','fr','it','rm'], null),
('FC Meiringen', 'fc-meiringen', 'Fussballverein mit Training und Spielen.', 'sport', null, 'fc@meiringen.ch', null, 'Sportplatz Meiringen', 46.7300, 8.1920, array['de','gsw'], null);

insert into public.events (organization_id, title, slug, description, category, start_date, end_date, location_name, address, latitude, longitude, price, language, is_recurring, status) values
((select id from public.organizations where slug = 'kulturverein-meiringen'), 'Alpine Kulturabend', 'alpine-kulturabend', 'Ein Abend mit regionaler Musik, Kunst und Geschichten aus dem Haslital.', 'culture', now() + interval '5 days', now() + interval '5 days' + interval '3 hours', 'Kulturhaus Meiringen', 'Bahnhofstrasse 1, 3860 Meiringen', 46.7275, 8.1875, 'CHF 15', 'de', false, 'published'),
((select id from public.organizations where slug = 'integrationszentrum-oberhasli'), 'Deutschkurs A1 – Anfänger', 'deutschkurs-a1-anfaenger', 'Einführungskurs Deutsch für Neuankömmlinge. Wöchentlich dienstags.', 'integration', now() + interval '7 days', now() + interval '7 days' + interval '2 hours', 'Integrationszentrum', 'Kirchgasse 5, 3860 Meiringen', 46.7268, 8.1862, 'Gratis', 'de', true, 'published'),
((select id from public.organizations where slug = 'integrationszentrum-oberhasli'), 'Portugiesisch-Treff', 'portugiesisch-treff', 'Informeller Sprachaustausch auf Portugiesisch und Deutsch.', 'integration', now() + interval '10 days', now() + interval '10 days' + interval '2 hours', 'Integrationszentrum', 'Kirchgasse 5, 3860 Meiringen', 46.7268, 8.1862, 'Gratis', 'pt', true, 'published'),
((select id from public.organizations where slug = 'sportclub-haslital'), 'Volleyball Turnier', 'volleyball-turnier', 'Regionales Volleyball-Turnier für gemischte Teams.', 'sport', now() + interval '12 days', now() + interval '12 days' + interval '6 hours', 'Sporthalle Meiringen', 'Hauptstrasse 12, 3860 Meiringen', 46.7280, 8.1880, 'CHF 20/Team', 'de', false, 'published'),
((select id from public.organizations where slug = 'gemeinde-meiringen'), 'Wochenmarkt Meiringen', 'wochenmarkt-meiringen', 'Regionaler Markt mit lokalen Produkten und Spezialitäten.', 'market', now() + interval '3 days', now() + interval '3 days' + interval '5 hours', 'Dorfplatz', 'Dorfplatz, 3860 Meiringen', 46.7272, 8.1870, 'Gratis', 'de', true, 'published'),
((select id from public.organizations where slug = 'gemeinde-meiringen'), 'Haslitaler Herbstfest', 'haslitaler-herbstfest', 'Traditionelles Herbstfest mit Musik, Essen und Handwerk.', 'festival', now() + interval '20 days', now() + interval '20 days' + interval '8 hours', 'Dorfplatz Meiringen', 'Dorfplatz, 3860 Meiringen', 46.7272, 8.1870, 'Gratis', 'de', false, 'published'),
((select id from public.organizations where slug = 'musikgesellschaft-meiringen'), 'Konzert im Kulturhaus', 'konzert-im-kulturhaus', 'Frühjahrskonzert der Musikgesellschaft Meiringen.', 'music', now() + interval '15 days', now() + interval '15 days' + interval '2 hours', 'Kulturhaus', 'Bahnhofstrasse 1, 3860 Meiringen', 46.7275, 8.1875, 'CHF 25', 'de', false, 'published'),
((select id from public.organizations where slug = 'naturfreunde-haslital'), 'Geführte Wanderung Reichenbachfall', 'gefuehrte-wanderung-reichenbachfall', 'Wanderung zum berühmten Reichenbachfall mit erfahrenem Guide.', 'nature', now() + interval '8 days', now() + interval '8 days' + interval '4 hours', 'Treffpunkt Bahnhof Meiringen', 'Bahnhof Meiringen', 46.7275, 8.1875, 'CHF 10', 'de', false, 'published'),
((select id from public.organizations where slug = 'seniorenverein-meiringen'), 'Kaffee und Kuchen Nachmittag', 'kaffee-und-kuchen-nachmittag', 'Gemütlicher Nachmittag für Senioren mit Kaffee, Kuchen und Gesellschaft.', 'social', now() + interval '6 days', now() + interval '6 days' + interval '3 hours', 'Gemeindesaal', 'Schulhausweg 2, 3860 Meiringen', 46.7265, 8.1855, 'Gratis', 'de', true, 'published'),
((select id from public.organizations where slug = 'fc-meiringen'), 'Heimspiel FC Meiringen', 'heimspiel-fc-meiringen', 'Liga-Spiel des FC Meiringen.', 'sport', now() + interval '14 days', now() + interval '14 days' + interval '2 hours', 'Sportplatz Meiringen', 'Sportplatz Meiringen', 46.7300, 8.1920, 'CHF 10', 'de', false, 'published'),
((select id from public.organizations where slug = 'volksschule-meiringen'), 'Elternabend Integration', 'elternabend-integration', 'Informationsabend für Eltern zu Integrationsangeboten.', 'education', now() + interval '18 days', now() + interval '18 days' + interval '2 hours', 'Volksschule Meiringen', 'Schulhausstrasse 8, 3860 Meiringen', 46.7285, 8.1890, 'Gratis', 'de', false, 'published'),
((select id from public.organizations where slug = 'brass-band-haslital'), 'Open-Air Konzert', 'open-air-konzert', 'Sommerkonzert im Freien mit der Brass Band Haslital.', 'music', now() + interval '25 days', now() + interval '25 days' + interval '3 hours', 'Dorfplatz', 'Dorfplatz, 3860 Meiringen', 46.7272, 8.1870, 'Gratis', 'de', false, 'published'),
((select id from public.organizations where slug = 'integrationszentrum-oberhasli'), 'Französischkurs B1', 'franzoesischkurs-b1', 'Mittelstufenkurs Französisch für den Alltag.', 'integration', now() + interval '9 days', now() + interval '9 days' + interval '2 hours', 'Integrationszentrum', 'Kirchgasse 5, 3860 Meiringen', 46.7268, 8.1862, 'Gratis', 'fr', true, 'published'),
((select id from public.organizations where slug = 'gemeinde-meiringen'), 'Weihnachtsmarkt (Vorschau)', 'weihnachtsmarkt-vorschau', 'Vorab-Information zum jährlichen Weihnachtsmarkt.', 'market', now() + interval '60 days', now() + interval '60 days' + interval '6 hours', 'Dorfplatz', 'Dorfplatz, 3860 Meiringen', 46.7272, 8.1870, 'Gratis', 'de', false, 'draft'),
((select id from public.organizations where slug = 'kulturverein-meiringen'), 'Theaterabend: Sherlock Holmes', 'theaterabend-sherlock-holmes', 'Theaterstück inspiriert von Sherlock Holmes und dem Reichenbachfall.', 'culture', now() + interval '22 days', now() + interval '22 days' + interval '3 hours', 'Kulturhaus Meiringen', 'Bahnhofstrasse 1, 3860 Meiringen', 46.7275, 8.1875, 'CHF 30', 'de', false, 'published');

insert into public.scraping_sources (name, url, type, active) values
('Meiringen Gemeinde Events', 'https://www.meiringen.ch/veranstaltungen', 'generic', true),
('Haslital Tourism', 'https://www.haslital.ch/de/veranstaltungen', 'generic', true);
