-- Real Meiringen & Haslital Vereine (replaces placeholder seed organizations)
-- Sources: meiringen.ch, haslital-brienz.ch, vereinsverzeichnis.ch

delete from public.events;
delete from public.organizations;

insert into public.organizations (
  name, slug, description, category, website_url, email, phone, address,
  latitude, longitude, languages, image_url, source_url
) values
(
  'Musikgesellschaft Meiringen',
  'musikgesellschaft-meiringen',
  'Seit 1875 aktiv: Bläsercorps und Tambouren mit Frühlingskonzert, Ständchen und Auftritten in der Region.',
  'music',
  'https://mgmeiringen.ch',
  null,
  null,
  '3860 Meiringen',
  46.7275, 8.1875,
  array['de','gsw'],
  '/brand/org-logos/mgmeiringen.ch.png',
  'https://mgmeiringen.ch'
),
(
  'Jodlerklub Meiringen',
  'jodlerklub-meiringen',
  'Gegründet 1944. Pflegt Jodeln und Brauchtum mit wöchentlichen Proben und Jahreskonzert am 1.-März-Wochenende.',
  'music',
  'https://www.meiringen.ch/vereinsliste/24032',
  'presi@jkmeiringen.ch',
  '+41 79 104 46 30',
  'Zaun 5, 3860 Meiringen',
  46.7268, 8.1868,
  array['de','gsw'],
  '/brand/org-logos/meiringen-ch.png',
  'https://www.meiringen.ch/vereinsliste/24032'
),
(
  'Trachtengruppe Oberhasli',
  'trachtengruppe-oberhasli',
  'Pflege von Haslitracht, Volkstanz, Volkslied und Volkstheater in Meiringen und der Region.',
  'culture',
  'https://www.meiringen.ch/vereinsliste/24398',
  'hemahe@uewin.ch',
  '+41 33 971 61 64',
  'Allmendstrasse 8, 3860 Meiringen',
  46.7272, 8.1865,
  array['de','gsw','rm'],
  '/brand/org-logos/meiringen-ch.png',
  'https://www.meiringen.ch/vereinsliste/24398'
),
(
  'Männerchor Sängerbund Meiringen',
  'maennerchor-saengerbund-meiringen',
  'Traditioneller Männerchor mit Auftritten und Gesang in Meiringen.',
  'music',
  null,
  null,
  '+41 33 971 27 52',
  '3860 Meiringen',
  46.7278, 8.1880,
  array['de','gsw'],
  '/brand/org-logos/haslital-brienz-ch.png',
  'https://www.haslital-brienz.ch/vereine'
),
(
  'Frauenchor Meiringen',
  'frauenchor-meiringen',
  'Frauenchor für klassische und volkstümliche Chormusik in Meiringen.',
  'music',
  null,
  null,
  '+41 33 971 65 74',
  '3860 Meiringen',
  46.7265, 8.1872,
  array['de','gsw'],
  '/brand/org-logos/haslital-brienz-ch.png',
  'https://www.haslital-brienz.ch/vereine'
),
(
  'Theatergruppe Glinggige',
  'theatergruppe-glinggige',
  'Lokale Theatergruppe mit Produktionen und Auftritten in Meiringen.',
  'culture',
  null,
  null,
  '+41 79 831 82 64',
  '3860 Meiringen',
  46.7280, 8.1860,
  array['de','gsw'],
  '/brand/org-logos/meiringen-ch.png',
  'https://vereinsverzeichnis.ch/vereine-kanton/vereine-be/category/berninterlakenoberhaslimeiringen'
),
(
  'Kino+ Meiringen',
  'kino-meiringen',
  'Gemeinnütziger Kulturverein: Kino, Kleinkunst, Konzerte und Begegnungsräume im Herzen von Meiringen.',
  'culture',
  'https://www.kino-meiringen.ch',
  null,
  null,
  'Bahnhofstrasse 20, 3860 Meiringen',
  46.7270, 8.1870,
  array['de','gsw','en'],
  '/brand/org-logos/kino-meiringen.ch.png',
  'https://www.kino-meiringen.ch/unser-kino'
),
(
  'Museumsverein der Landschaft Hasli',
  'museumsverein-haslital',
  'Trägerverein des Hasli Museums — Bewahrung und Vermittlung regionaler Geschichte.',
  'culture',
  null,
  null,
  null,
  '3860 Meiringen',
  46.7273, 8.1885,
  array['de','gsw','en'],
  '/brand/org-logos/meiringen-ch.png',
  'https://vereinsverzeichnis.ch/vereine-kanton/vereine-be/category/berninterlakenoberhaslimeiringen'
),
(
  'ART & CULTURE COMMUNITY',
  'art-culture-community',
  'Gemeinschaft für Kunst und Kultur im Haslital — Vernetzung kreativer Akteure.',
  'culture',
  null,
  null,
  '+41 78 306 28 64',
  '3860 Meiringen',
  46.7282, 8.1890,
  array['de','en'],
  '/brand/org-logos/haslital-brienz-ch.png',
  'https://www.haslital-brienz.ch/vereine'
),
(
  'Fotoclub Haslital',
  'fotoclub-haslital',
  'Fotografie-Club für Hobby- und ambitionierte Fotografen in der Region Haslital.',
  'culture',
  null,
  null,
  '+41 79 372 63 55',
  '3860 Meiringen',
  46.7260, 8.1888,
  array['de'],
  '/brand/org-logos/haslital-brienz-ch.png',
  'https://www.haslital-brienz.ch/vereine'
),
(
  'FV Oberhasli',
  'fv-oberhasli',
  'Förderverein für Brauchtum, Feste und regionale Kultur im Oberhasli.',
  'culture',
  null,
  null,
  null,
  '3860 Meiringen',
  46.7276, 8.1862,
  array['de','gsw'],
  '/brand/org-logos/meiringen-ch.png',
  'https://www.localcities.ch/de/vereine/meiringen/1665'
),
(
  'Gemeinnütziger Verein Meiringen',
  'gemeinnuetziger-verein-meiringen',
  'Gemeinnütziger Verein für soziale und gesellschaftliche Projekte in Meiringen.',
  'social',
  null,
  null,
  '+41 79 445 04 38',
  '3860 Meiringen',
  46.7262, 8.1858,
  array['de','gsw'],
  '/brand/org-logos/haslital-brienz-ch.png',
  'https://www.haslital-brienz.ch/vereine'
),
(
  'Turnverein Meiringen',
  'turnverein-meiringen',
  'Turnen, Volleyball und Laufsport für Kinder, Aktive und Senioren — inkl. TBO-Turniere.',
  'sport',
  'https://www.tvmeiringen.ch',
  null,
  null,
  'Turnhalle Meiringen, 3860 Meiringen',
  46.7290, 8.1900,
  array['de','gsw'],
  '/brand/org-logos/tvmeiringen.ch.png',
  'https://www.tvmeiringen.ch'
),
(
  'Schwingklub Meiringen',
  'schwingklub-meiringen',
  'Seit 1931: Schwingen mit Haslitaler Jungschwingertag und Schwing- und Älplerfest Engstlenalp.',
  'sport',
  'https://schwingklub-meiringen.ch',
  'info@schwingklub-meiringen.ch',
  '+41 79 673 19 83',
  'Langachristrasse 26, 3855 Brienz',
  46.7285, 8.1910,
  array['de','gsw'],
  '/brand/org-logos/schwingklub-meiringen.ch.png',
  'https://schwingklub-meiringen.ch'
),
(
  'Schwingerfreunde Meiringen',
  'schwingerfreunde-meiringen',
  'Freunde und Förderer des Schwingens in Meiringen.',
  'sport',
  null,
  null,
  '+41 79 510 58 46',
  '3860 Meiringen',
  46.7288, 8.1895,
  array['de','gsw'],
  '/brand/org-logos/haslital-brienz-ch.png',
  'https://www.haslital-brienz.ch/vereine'
),
(
  'Tennisclub Meiringen',
  'tennisclub-meiringen',
  'Alpines Tenniscenter: Tennis, Padel, Badminton und Pickleball im Haslital.',
  'sport',
  'https://www.tennismeiringen.ch',
  null,
  null,
  'Sportplatzweg, 3860 Meiringen',
  46.7300, 8.1920,
  array['de','en'],
  '/brand/org-logos/tennismeiringen.ch.png',
  'https://www.tennismeiringen.ch'
),
(
  'SV Meiringen',
  'sv-meiringen',
  'Fussballverein mit Training und Spielbetrieb für die Region Meiringen.',
  'sport',
  null,
  null,
  null,
  'Sportplatz Meiringen, 3860 Meiringen',
  46.7310, 8.1930,
  array['de','gsw'],
  '/brand/org-logos/meiringen-ch.png',
  'https://www.localcities.ch/de/vereine/meiringen/1665'
),
(
  'Curling Club Oberhasli',
  'curling-club-oberhasli',
  'Curling für Einsteiger und Fortgeschrittene im Oberhasli.',
  'sport',
  null,
  null,
  '+41 79 376 58 64',
  '3860 Meiringen',
  46.7258, 8.1845,
  array['de','en'],
  '/brand/org-logos/meiringen-ch.png',
  'https://vereinsverzeichnis.ch/vereine-kanton/vereine-be/category/berninterlakenoberhaslimeiringen'
),
(
  'Nordischer Skiclub Oberhasli',
  'nordischer-skiclub-oberhasli',
  'Langlauf und nordische Disziplinen im Skigebiet und Haslital.',
  'sport',
  null,
  null,
  null,
  '3860 Meiringen',
  46.7320, 8.1950,
  array['de','gsw','en'],
  '/brand/org-logos/meiringen-ch.png',
  'https://vereinsverzeichnis.ch/vereine-kanton/vereine-be/category/berninterlakenoberhaslimeiringen'
),
(
  'Karate Kickboxing Meiringen/Spiez',
  'karate-kickboxing-meiringen',
  'Kampfsport-Training: Karate und Kickboxing für Kinder und Erwachsene.',
  'sport',
  null,
  null,
  null,
  '3860 Meiringen',
  46.7268, 8.1905,
  array['de','en'],
  '/brand/org-logos/meiringen-ch.png',
  'https://vereinsverzeichnis.ch/vereine-kanton/vereine-be/category/berninterlakenoberhaslimeiringen'
),
(
  'Kanu Klub Berner Oberland',
  'kanu-klub-berner-oberland',
  'Kanu- und Kayakfahren auf Flüssen und Seen im Berner Oberland.',
  'sport',
  null,
  null,
  null,
  '3860 Meiringen',
  46.7250, 8.1830,
  array['de','en'],
  '/brand/org-logos/meiringen-ch.png',
  'https://vereinsverzeichnis.ch/vereine-kanton/vereine-be/category/berninterlakenoberhaslimeiringen'
),
(
  'Tauchclub Berner Oberland',
  'tauchclub-berner-oberland',
  'Tauchsport und Unterwasseraktivitäten für Mitglieder aus der Region.',
  'sport',
  null,
  null,
  null,
  '3860 Meiringen',
  46.7245, 8.1825,
  array['de','en'],
  '/brand/org-logos/meiringen-ch.png',
  'https://vereinsverzeichnis.ch/vereine-kanton/vereine-be/category/berninterlakenoberhaslimeiringen'
),
(
  'SAC Oberhasli',
  'sac-oberhasli',
  'Schweizer Alpen-Club Sektion Oberhasli: Wandern, Bergsteigen und Hütten.',
  'nature',
  'https://www.sac-cas.ch',
  null,
  null,
  '3860 Meiringen',
  46.7330, 8.1960,
  array['de','en','fr','it'],
  '/brand/org-logos/sac-cas.ch.png',
  'https://www.localcities.ch/de/vereine/meiringen/1665'
),
(
  'UHC Brienz-Oberhasli',
  'uhc-brienz-oberhasli',
  'Unihockey-Club für Junioren und Erwachsene in Brienz und Oberhasli.',
  'sport',
  null,
  null,
  null,
  '3860 Meiringen',
  46.7295, 8.1915,
  array['de','gsw'],
  '/brand/org-logos/meiringen-ch.png',
  'https://www.localcities.ch/de/vereine/meiringen/1665'
),
(
  'Verein Pro Alpbachschlucht',
  'verein-pro-alpbachschlucht',
  'Erhalt und Förderung der Aareschlucht und des Alpbachschlucht-Wegs bei Meiringen.',
  'nature',
  null,
  null,
  null,
  'Aareschlucht, 3860 Meiringen',
  46.7200, 8.2050,
  array['de','gsw','en'],
  '/brand/org-logos/meiringen-ch.png',
  'https://vereinsverzeichnis.ch/vereine-kanton/vereine-be/category/berninterlakenoberhaslimeiringen'
),
(
  'Kynologischer Verein Haslital Meiringen',
  'kynologischer-verein-haslital',
  'Hundesport und kynologische Aktivitäten für Hundebesitzer im Haslital.',
  'social',
  null,
  null,
  null,
  '3860 Meiringen',
  46.7255, 8.1840,
  array['de'],
  '/brand/org-logos/meiringen-ch.png',
  'https://vereinsverzeichnis.ch/vereine-kanton/vereine-be/category/berninterlakenoberhaslimeiringen'
),
(
  'AMC Auto und Moto Club Haslital',
  'amc-auto-moto-club-haslital',
  'Auto- und Motorrad-Club für Enthusiasten im Haslital.',
  'other',
  null,
  null,
  '+41 77 416 27 87',
  '3860 Meiringen',
  46.7240, 8.1815,
  array['de'],
  '/brand/org-logos/haslital-brienz-ch.png',
  'https://www.haslital-brienz.ch/vereine'
),
(
  'Fluggruppe Oberhasli-Brienz (FLOB)',
  'fluggruppe-flob',
  'Fluggruppe für Modell- und Luftsport-Begeisterte in Oberhasli und Brienz.',
  'other',
  null,
  null,
  null,
  '3860 Meiringen',
  46.7340, 8.1970,
  array['de'],
  '/brand/org-logos/meiringen-ch.png',
  'https://vereinsverzeichnis.ch/vereine-kanton/vereine-be/category/berninterlakenoberhaslimeiringen'
),
(
  'Schützengesellschaft Balm',
  'schuetzengesellschaft-balm',
  'Traditionelle Schützengesellschaft in Meiringen-Balm.',
  'culture',
  null,
  null,
  null,
  'Balm, 3860 Meiringen',
  46.7350, 8.1800,
  array['de','gsw'],
  '/brand/org-logos/meiringen-ch.png',
  'https://vereinsverzeichnis.ch/vereine-kanton/vereine-be/category/berninterlakenoberhaslimeiringen'
),
(
  'Schützengesellschaft Hausen',
  'schuetzengesellschaft-hausen',
  'Traditionelle Schützengesellschaft in Meiringen-Hausen.',
  'culture',
  null,
  null,
  null,
  'Hausen, 3860 Meiringen',
  46.7360, 8.1790,
  array['de','gsw'],
  '/brand/org-logos/meiringen-ch.png',
  'https://vereinsverzeichnis.ch/vereine-kanton/vereine-be/category/berninterlakenoberhaslimeiringen'
),
(
  'Pfadfinder St. Christophorus Meiringen-Brienz',
  'pfadfinder-meiringen-brienz',
  'Pfadi-Abteilung für Kinder und Jugendliche in Meiringen und Brienz.',
  'education',
  null,
  null,
  null,
  '3860 Meiringen',
  46.7270, 8.1880,
  array['de','gsw'],
  '/brand/org-logos/meiringen-ch.png',
  'https://vereinsverzeichnis.ch/vereine-kanton/vereine-be/category/berninterlakenoberhaslimeiringen'
),
(
  'Mütter- und Väterberatung Interlaken-Oberhasli',
  'muetter-vaeterberatung-oberhasli',
  'Beratung und Unterstützung für Eltern in der Region Interlaken-Oberhasli.',
  'social',
  null,
  null,
  null,
  '3860 Meiringen',
  46.7265, 8.1878,
  array['de','gsw','en'],
  '/brand/org-logos/meiringen-ch.png',
  'https://vereinsverzeichnis.ch/vereine-kanton/vereine-be/category/berninterlakenoberhaslimeiringen'
),
(
  'Verein Tagesfamilien Interlaken-Oberhasli',
  'tagesfamilien-oberhasli',
  'Netzwerk von Tagesfamilien und Familienpflege in der Region.',
  'social',
  null,
  null,
  null,
  '3860 Meiringen',
  46.7263, 8.1875,
  array['de'],
  '/brand/org-logos/meiringen-ch.png',
  'https://vereinsverzeichnis.ch/vereine-kanton/vereine-be/category/berninterlakenoberhaslimeiringen'
),
(
  'Procap Regionalstelle Interlaken-Oberhasli',
  'procap-oberhasli',
  'Selbsthilfeorganisation für Menschen mit körperlicher Behinderung.',
  'social',
  'https://www.procap.ch',
  null,
  null,
  '3860 Meiringen',
  46.7260, 8.1870,
  array['de','gsw','fr'],
  '/brand/org-logos/procap.ch.png',
  'https://vereinsverzeichnis.ch/vereine-kanton/vereine-be/category/berninterlakenoberhaslimeiringen'
),
(
  'Gemeinde Meiringen',
  'gemeinde-meiringen',
  'Offizielle Gemeindeverwaltung: Veranstaltungen, Märkte, Kultur und Bürgerservice.',
  'festival',
  'https://www.meiringen.ch',
  'info@meiringen.ch',
  '+41 33 972 11 11',
  'Rathaus, Bahnhofstrasse 20, 3860 Meiringen',
  46.7270, 8.1868,
  array['de','gsw','en','fr','it','rm'],
  '/brand/org-logos/meiringen-ch.png',
  'https://www.meiringen.ch/vereinsliste'
);

-- Sample events linked to real organizations
insert into public.events (
  organization_id, title, slug, description, category, start_date, end_date,
  location_name, address, latitude, longitude, price, language, is_recurring, status
) values
(
  (select id from public.organizations where slug = 'musikgesellschaft-meiringen'),
  'Sommerabend Innertkirchen',
  'mgm-sommerabend-innertkirchen',
  'Musikgesellschaft Meiringen beim Sommerabend in Innertkirchen.',
  'music',
  now() + interval '45 days', now() + interval '45 days' + interval '2 hours',
  'Innertkirchen', 'Innertkirchen', 46.7000, 8.2300, 'Gratis', 'de', false, 'published'
),
(
  (select id from public.organizations where slug = 'jodlerklub-meiringen'),
  'Jodlerklub Probe (Mittwoch)',
  'jodlerklub-probe-mittwoch',
  'Wöchentliche Probe im Kirchgemeindesaal — neue Mitglieder willkommen.',
  'music',
  now() + interval '3 days', now() + interval '3 days' + interval '2 hours',
  'Kirchgemeindesaal', '3860 Meiringen', 46.7268, 8.1868, 'Gratis', 'de', true, 'published'
),
(
  (select id from public.organizations where slug = 'kino-meiringen'),
  'Kino+ Programm',
  'kino-plus-programm',
  'Aktuelles Kinoprogramm und Kulturveranstaltungen im Kino Meiringen.',
  'culture',
  now() + interval '2 days', now() + interval '2 days' + interval '3 hours',
  'Kino+ Meiringen', 'Bahnhofstrasse 20, 3860 Meiringen', 46.7270, 8.1870, 'CHF 15', 'de', false, 'published'
),
(
  (select id from public.organizations where slug = 'turnverein-meiringen'),
  'Laufsporttag Meiringen',
  'tv-meiringen-laufsporttag',
  'Laufsporttag im Rahmen des Strassenfests: Sprint, Mittelstrecken, Staffel Jung+Alt.',
  'sport',
  now() + interval '30 days', now() + interval '30 days' + interval '5 hours',
  'Meiringen', '3860 Meiringen', 46.7290, 8.1900, 'Gratis', 'de', false, 'published'
),
(
  (select id from public.organizations where slug = 'schwingklub-meiringen'),
  'Haslitaler Jungschwingertag',
  'haslitaler-jungschwingertag',
  'Jährlicher Jungschwingertag des Schwingklubs Meiringen.',
  'sport',
  now() + interval '60 days', now() + interval '60 days' + interval '8 hours',
  'Meiringen', '3860 Meiringen', 46.7285, 8.1910, 'CHF 10', 'de', false, 'published'
),
(
  (select id from public.organizations where slug = 'tennisclub-meiringen'),
  'Tennis Grand Prix Meiringen',
  'tennis-grand-prix-meiringen',
  'Teil des grössten Schweizer Breitensport-Tennisturniers.',
  'sport',
  now() + interval '20 days', now() + interval '20 days' + interval '6 hours',
  'Alpines Tenniscenter', 'Sportplatzweg, 3860 Meiringen', 46.7300, 8.1920, 'CHF 25', 'de', false, 'published'
),
(
  (select id from public.organizations where slug = 'gemeinde-meiringen'),
  'Wochenmarkt Dorfplatz',
  'gemeinde-wochenmarkt-dorfplatz',
  'Regionaler Wochenmarkt mit lokalen Produkten auf dem Dorfplatz.',
  'market',
  now() + interval '4 days', now() + interval '4 days' + interval '5 hours',
  'Dorfplatz', 'Dorfplatz, 3860 Meiringen', 46.7272, 8.1870, 'Gratis', 'de', true, 'published'
),
(
  (select id from public.organizations where slug = 'gemeinde-meiringen'),
  'Haslitaler Herbstfest',
  'gemeinde-herbstfest',
  'Traditionelles Herbstfest mit Musik, Essen und Handwerk.',
  'festival',
  now() + interval '90 days', now() + interval '90 days' + interval '8 hours',
  'Dorfplatz Meiringen', 'Dorfplatz, 3860 Meiringen', 46.7272, 8.1870, 'Gratis', 'de', false, 'published'
),
(
  (select id from public.organizations where slug = 'sac-oberhasli'),
  'SAC Wanderung Oberhasli',
  'sac-wanderung-oberhasli',
  'Geführte Wanderung mit der SAC Sektion Oberhasli.',
  'nature',
  now() + interval '10 days', now() + interval '10 days' + interval '6 hours',
  'Treffpunkt Bahnhof Meiringen', 'Bahnhof Meiringen', 46.7275, 8.1875, 'Gratis', 'de', false, 'published'
),
(
  (select id from public.organizations where slug = 'theatergruppe-glinggige'),
  'Theaterprobe Glinggige',
  'theatergruppe-glinggige-probe',
  'Offene Probe der Theatergruppe Glinggige — Interessierte willkommen.',
  'culture',
  now() + interval '8 days', now() + interval '8 days' + interval '3 hours',
  'Meiringen', '3860 Meiringen', 46.7280, 8.1860, 'Gratis', 'de', true, 'published'
);
