-- Smart cover images discovered from organization websites
-- Generated by scripts/discover-org-cover-images.mjs

update public.organizations set
  cover_image_url = 'https://www.karate-kickboxing.ch/images/content/eyecatcher/default/99team_wmac.jpg'
where slug = 'karate-kickboxing-meiringen';
update public.organizations set
  cover_image_url = 'https://static.wixstatic.com/media/11062b_19297116e92043588104e344620590ca~mv2.jpg'
where slug = 'kino-meiringen';
update public.organizations set
  cover_image_url = 'https://wp.mgbrienzwiler.ch/wordpress/wp-content/uploads/2022/06/cropped-Beginnerband-2018-scaled-1.jpg'
where slug = 'musikfoerderverein-brienzwiler';
update public.organizations set
  cover_image_url = 'https://www.mvb-be.ch/uploads/media/home-hero/05/1565-hero_bild_mvb.jpg?v=1-0'
where slug = 'muetter-vaeterberatung-oberhasli';
update public.organizations set
  cover_image_url = 'https://nscoberhasli.ch/wp-content/uploads/2025/01/img_4953.jpg'
where slug = 'nordischer-skiclub-oberhasli';
update public.organizations set
  cover_image_url = 'https://www.pfadimeiringenbrienz.ch/theme/stchrist/images/11.jpg'
where slug = 'pfadfinder-meiringen-brienz';
update public.organizations set
  cover_image_url = 'https://www.tcbeo.ch/images/banners/121829946_1711960738963712_4046572903172461061_n.jpg'
where slug = 'tauchclub-berner-oberland';
update public.organizations set
  cover_image_url = 'https://volkstheaterfestival.ch/fileadmin/images/programm/2026/diverse/vtfm-2019-eroeffnung-david-birri.jpg'
where slug = 'theatergruppe-glinggige';
update public.organizations set
  cover_image_url = 'https://static.wixstatic.com/media/a63353_c8bebf1a16de4494b0b0e2cec5a734e5~mv2.jpeg'
where slug = 'turnverein-meiringen';
update public.organizations set
  cover_image_url = 'https://alpbachschlucht.ch/wp-content/uploads/2020/07/alpbachschlucht_headerbild_200720_2.jpg'
where slug = 'verein-pro-alpbachschlucht';
