-- Confirmed Haslital organization additions from official / corroborated sources

insert into public.organizations (
  name, slug, description, category, website_url, email, phone, address,
  latitude, longitude, languages, image_url, source_url, locality
) values
(
  'Samariterverein Meiringen',
  'samariterverein-meiringen',
  'Samariterverein mit Kurswesen, Blutspendeaktionen und Sanitätsdiensten in Meiringen.',
  'social',
  'https://www.samariter-meiringen.ch',
  'info@samariter-meiringen.ch',
  '+41 78 717 18 30',
  '3860 Meiringen',
  46.7275, 8.1875,
  array['de','gsw'],
  'https://www.google.com/s2/favicons?domain=samariter-meiringen.ch&sz=128',
  'https://www.meiringen.ch/vereinsliste/23663',
  'meiringen'
),
(
  'Reitverein Oberhasli Brienz',
  'reitverein-oberhasli-brienz',
  'Reitverein für Pferdesport, Freizeitreiten und Reitanlässe im Oberhasli und Brienz.',
  'sport',
  'https://www.reitverein-oberhasli-brienz.ch',
  'info@reitverein-oberhasli-brienz.ch',
  '+41 79 917 90 39',
  'Funtenenstrasse 5, 3860 Meiringen',
  46.7275, 8.1875,
  array['de','gsw'],
  'https://www.google.com/s2/favicons?domain=reitverein-oberhasli-brienz.ch&sz=128',
  'https://www.meiringen.ch/vereinsliste/23537',
  'meiringen'
),
(
  'Kindergartenverein Meiringen',
  'kindergartenverein-meiringen',
  'Verein zur Unterstützung der Kindergärten in Meiringen über Brockenverkauf, Spenden und Mitgliederbeiträge.',
  'education',
  null,
  'kindergartenverein.meiringen@gmx.ch',
  '+41 79 246 65 60',
  '3860 Meiringen',
  46.7275, 8.1875,
  array['de','gsw'],
  '/brand/org-logos/meiringen-ch.png',
  'https://www.meiringen.ch/vereinsliste/29353',
  'meiringen'
),
(
  'Berner KMU Oberhasli',
  'berner-kmu-oberhasli',
  'Regionaler Wirtschaftsverein für KMU im Oberhasli mit Netzwerk-, Politik- und Standortförderung.',
  'other',
  'https://www.kmu-oberhasli.ch',
  'info@kmu-oberhasli.ch',
  null,
  'Bahnhofstrasse 20, 3860 Meiringen',
  46.7275, 8.1875,
  array['de'],
  'https://www.google.com/s2/favicons?domain=kmu-oberhasli.ch&sz=128',
  'https://www.meiringen.ch/vereinsliste/31127',
  'meiringen'
),
(
  'DVO Detaillistenverein Oberhasli',
  'dvo-detaillistenverein-oberhasli',
  'Detaillistenverein für das lokale Gewerbe und den Dorfhandel in Meiringen.',
  'other',
  null,
  'info@papeterie-jenny.ch',
  '033 971 13 07',
  'Postfach 543, 3860 Meiringen',
  46.7275, 8.1875,
  array['de'],
  '/brand/org-logos/meiringen-ch.png',
  'https://www.meiringen.ch/vereinsliste/38719',
  'meiringen'
),
(
  'Fischereiverein Oberhasli',
  'fischereiverein-oberhasli',
  'Fischereiverein für Gewässerpflege, Fischbestand und Jugendarbeit im Oberhasli.',
  'nature',
  'https://www.fv-oberhasli.ch',
  'kurt.zumbrunn@bamboorods.ch',
  '+41 77 504 82 91',
  'Reichenbachsäge 427E, 3860 Meiringen',
  46.7275, 8.1875,
  array['de'],
  'https://www.google.com/s2/favicons?domain=fv-oberhasli.ch&sz=128',
  'https://www.meiringen.ch/vereinsliste/86678',
  'meiringen'
),
(
  'Dynamo Wiggäfisch',
  'dynamo-wiggaefisch',
  'Junge Hasler, die das Wochenende- und Freizeitangebot im Hasli mitgestalten.',
  'social',
  null,
  'kevin.kohler.scott@gmail.com',
  '+41 79 895 39 10',
  'Obersteinstrasse 6, 3860 Schattenhalb',
  46.71, 8.21,
  array['de','gsw'],
  '/brand/org-logos/meiringen-ch.png',
  'https://www.meiringen.ch/vereinsliste/99346',
  'schattenhalb'
),
(
  'Ringclub Oberhasli',
  'ringclub-oberhasli',
  'Ringerclub aus dem Oberhasli mit Nachwuchs- und Wettkampfaktivitäten.',
  'sport',
  null,
  null,
  '078 809 69 07',
  '3862 Innertkirchen',
  46.7, 8.23,
  array['de'],
  '/brand/org-logos/haslital-brienz-ch.png',
  'https://www.haslital-brienz.ch/vereine',
  'innertkirchen'
),
(
  'SLRG Sektion Thun-Oberland / Aussenstation Brienz-Meiringen',
  'slrg-sektion-thun-oberland-aussenstation-brienz-meiringen',
  'Rettungsschwimmen, Erste Hilfe und Wassertraining für die Region Brienz-Meiringen.',
  'sport',
  'https://slrg-thunoberland.ch/brienz-meiringen',
  'info@slrg-thunoberland.ch',
  null,
  '3600 Thun',
  46.73, 8.1,
  array['de'],
  'https://www.google.com/s2/favicons?domain=slrg-thunoberland.ch&sz=128',
  'https://www.meiringen.ch/vereinsliste/28562',
  'brienz'
)
on conflict (slug) do nothing;
